### ISSUE TITLE
Remove broken font "Source Code Pro" 

### ISSUE THREAD

**Issue by hcguersoy** [Homebrew/homebrew-cask-fonts#3973]
As stated in the issue #3972, the font "Source Code Pro" is broken in the upstream Google repository.

Due to that, remove it until it is fixed in upstream. 

Otherwise this will cause many problems on installations as this version of the font doesn't render correctly anymore, e.g. in Visual Code or Atom.

**Comment by vitorgalvao** [comment]
Simply removing this won’t work, because it will be added by the script which keeps these up-to-date. Please don’t be reactionary. The first step isn’t to shove workarounds whatever is convenient, but to try to get this resolved upstream, in the Google Fonts repo.

**Comment by hcguersoy** [comment]
Dear @vitorgalvao , 

IMHO this is not a matter of "reactionary" but preventing users from running into issues.
As you know these are bugs which are fixed already in the repository used before but the google repo is dead.

BTW, please excuse me if I acted too harshly in the other issue. This was not my intention and as a homebrew user for over ten years I really appreciate your work.

**Comment by vitorgalvao** [comment]
> this is not a matter of "reactionary"

That was absolutely the wrong word; I meant reactive/rushed and got some brain wires crossed.

> the google repo is dead.

[That’s demonstrably incorrect](https://github.com/google/fonts/commits/main). In [the last week alone](https://github.com/google/fonts/pulse/), of the 25 PRs opened 19 were merged, and of the 13 new issues only 5 remain open. Now that I look closer, I see [the issue in question](https://github.com/google/fonts/issues/1744) is not a PR. That makes it way simpler to understand why it wasn’t fixed yet! They have 1000 issues and only 33 PRs, which do you think they’ll do first and more eagerly: the ones which *increase* work or the ones which *save* work? Someone should submit a PR *to them* instead of submitting *to us*. As explained before, that’s the resolution that will fix it everywhere.

Also pinging @jsgv and @iandol.

> BTW, please excuse me if I acted too harshly in the other issue. This was not my intention and as a homebrew user for over ten years I really appreciate your work.

Thank you. Apology accepted. Pinging @carlocab.

**Comment by carlocab** [comment]
> BTW, please excuse me if I acted too harshly in the other issue. This was not my intention and as a homebrew user for over ten years I really appreciate your work.

Thank you. I'd like to apologise for being less than charitable as well in #3972.

**Comment by iandol** [comment]
I have created a tap with the Adobe versions that you can use. @carlocab —  the source-code-pro cask has the same name as the official one and that means you have to specify the full path:

https://github.com/iandol/homebrew-adobe-fonts

`brew install iandol/adobe-fonts/font-source-code-pro`

**Comment by vitorgalvao** [comment]
> The docs for taps mentions the naming conventions for formulae but not casks

There’s no difference.
